//! # Dashboard Telemetry & Observability
//!
//! This module provides a custom `tracing_subscriber::Layer` designed specifically
//! to power the Extrag Agentic Dashboard. Instead of just forwarding logs to stdout
//! or a file, this layer acts as an in-memory metric aggregator.
//!
//! It intercepts structured tracing events emitted across the `api`, `etl`, and `rag`
//! crates, extracts quantifiable fields (like token usage or data throughput), and
//! atomically updates a shared state. This state is then exposed safely via the REST API.

use serde::Serialize;
use std::sync::Arc;
use std::sync::atomic::{AtomicU64, Ordering};
use tracing::field::Visit;
use tracing::{Event, Subscriber};
use tracing_subscriber::Layer;
use std::collections::VecDeque;
use std::sync::RwLock;
use chrono::Local;

/// A single log entry captured for the dashboard.
#[derive(Debug, Clone, Serialize)]
pub struct LogEvent {
    pub timestamp: String,
    pub level: String,
    pub target: String,
    pub message: String,
}

/// A thread-safe, shared container tracking global engine metrics.
#[derive(Clone, Serialize)]
pub struct DashboardMetrics {
    /// Total number of tokens sent to the LLM (Prompt cost).
    pub total_prompt: Arc<AtomicU64>,
    /// Total number of tokens generated by the LLM (Response cost).
    pub total_completion: Arc<AtomicU64>,
    /// Total number of semantic vectors (chunks) successfully indexed into the vector database.
    pub total_chunks: Arc<AtomicU64>,
    /// Total byte throughput processed by the data extractors.
    pub total_bytes: Arc<AtomicU64>,
    /// Total number of search queries executed via the `/v1/retrieve` endpoint.
    pub total_retrievals: Arc<AtomicU64>,
    /// Cumulative count of system errors intercepted by the tracing layer (`tracing::Level::ERROR`).
    pub total_errors: Arc<AtomicU64>,
    /// Recent log events for the live activity feed.
    #[serde(serialize_with = "serialize_events")]
    pub events: Arc<RwLock<VecDeque<LogEvent>>>,
}

impl Default for DashboardMetrics {
    fn default() -> Self {
        Self {
            total_prompt: Arc::new(AtomicU64::new(0)),
            total_completion: Arc::new(AtomicU64::new(0)),
            total_chunks: Arc::new(AtomicU64::new(0)),
            total_bytes: Arc::new(AtomicU64::new(0)),
            total_retrievals: Arc::new(AtomicU64::new(0)),
            total_errors: Arc::new(AtomicU64::new(0)),
            events: Arc::new(RwLock::new(VecDeque::with_capacity(20))),
        }
    }
}

fn serialize_events<S>(
    events: &Arc<RwLock<VecDeque<LogEvent>>>,
    serializer: S,
) -> Result<S::Ok, S::Error>
where
    S: serde::Serializer,
{
    let events = events.read().unwrap();
    events.serialize(serializer)
}

/// A custom tracing layer that intercept LLM usage telemetry and maintain
/// a global cumulative counter for the current session.
pub struct DashboardTelemetryLayer {
    metrics: DashboardMetrics,
}

impl DashboardTelemetryLayer {
    pub fn new(metrics: DashboardMetrics) -> Self {
        Self { metrics }
    }
}

struct DashboardVisitor {
    prompt: u64,
    completion: u64,
    chunks: u64,
    bytes: u64,
    retrievals: u64,
    message: String,
}

impl Visit for DashboardVisitor {
    fn record_debug(&mut self, field: &tracing::field::Field, value: &dyn std::fmt::Debug) {
        let formatted = format!("{:?}", value);
        if let Ok(num) = formatted.parse::<u64>() {
            self.record_u64(field, num);
        }
    }

    fn record_u64(&mut self, field: &tracing::field::Field, value: u64) {
        match field.name() {
            "prompt_tokens" => self.prompt = value,
            "completion_tokens" => self.completion = value,
            "chunks_indexed" => self.chunks = value,
            "bytes_ingested" => self.bytes = value,
            "retrieval_query" => self.retrievals = value,
            _ => {}
        }
    }

    fn record_str(&mut self, field: &tracing::field::Field, value: &str) {
        if field.name() == "message" {
            self.message = value.to_string();
        }
    }

    fn record_i64(&mut self, field: &tracing::field::Field, value: i64) {
        if value >= 0 {
            self.record_u64(field, value as u64);
        }
    }
}

impl<S> Layer<S> for DashboardTelemetryLayer
where
    S: Subscriber,
{
    fn on_event(&self, event: &Event<'_>, _ctx: tracing_subscriber::layer::Context<'_, S>) {
        let mut visitor = DashboardVisitor {
            prompt: 0,
            completion: 0,
            chunks: 0,
            bytes: 0,
            retrievals: 0,
            message: String::new(),
        };
        event.record(&mut visitor);

        // Capture Log Event for Live Feed
        let level = event.metadata().level().to_string();
        let target = event.metadata().target().to_string();
        let message = if !visitor.message.is_empty() {
            visitor.message.clone()
        } else {
            format!("{:?}", event) // fallback if message not captured via record_str
        };

        // We filter out some very noisy/internal targets or we can keep them for "Agentic" feel
        if event.metadata().level() <= &tracing::Level::INFO || target.starts_with("extrag") || target.starts_with("rag") || target.starts_with("etl") {
            let mut events = self.metrics.events.write().unwrap();
            events.push_back(LogEvent {
                timestamp: Local::now().format("%H:%M:%S").to_string(),
                level: level.clone(),
                target: target.clone(),
                message: message.clone(),
            });

            if events.len() > 20 {
                events.pop_front();
            }
        }

        let mut printed = false;

        if event.metadata().level() == &tracing::Level::ERROR {
            self.metrics.total_errors.fetch_add(1, Ordering::Relaxed);
        }

        if visitor.prompt > 0 || visitor.completion > 0 {
            self.metrics
                .total_prompt
                .fetch_add(visitor.prompt, Ordering::Relaxed);
            self.metrics
                .total_completion
                .fetch_add(visitor.completion, Ordering::Relaxed);
            printed = true;
        }

        if visitor.chunks > 0 {
            self.metrics
                .total_chunks
                .fetch_add(visitor.chunks, Ordering::Relaxed);
            printed = true;
        }

        if visitor.bytes > 0 {
            self.metrics
                .total_bytes
                .fetch_add(visitor.bytes, Ordering::Relaxed);
            printed = true;
        }

        if visitor.retrievals > 0 {
            self.metrics
                .total_retrievals
                .fetch_add(visitor.retrievals, Ordering::Relaxed);
            printed = true;
        }

        if printed && event.metadata().target() != "extrag::telemetry" {
            let tp = self.metrics.total_prompt.load(Ordering::Relaxed);
            let tc = self.metrics.total_completion.load(Ordering::Relaxed);
            let chunks = self.metrics.total_chunks.load(Ordering::Relaxed);

            tracing::info!(
                target: "extrag::telemetry",
                "📊 CUMULATIVE TELEMETRY: {} tokens | {} chunks indexed",
                tp + tc,
                chunks
            );
        }
    }
}
